version: '3.8'
services:
  redis:
    image: "redis:7.0"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/var/lib/mysql
      - ./redis/data/redis.conf:/var/lib/redis/redis.conf
    command: redis-server /var/lib/redis/redis.conf
  mysql:
    image: "mysql:8.0.34"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
      - ./mysql/data:/var/lib/mysql
  rabbitmq-stomp:
    image: "rabbitmq:3.12"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
      
